### ISSUE TITLE
quotesAreSame std::domain_error type must be number, but is null

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#183] opened 2017-08-28 17:14 UTC
17:11:11.179489 GW bitfinex:
- autoBot: yes
- pair: xrpusd
- minTick: 0.00001000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
17:11:11.179985 DB /data/db/K.4.31.82.db loaded OK.
17:11:11.183175 TBP = 42192.81760026 XRP loaded from DB.
17:11:11.200266 Unable to calculate quote, missing fair value.
17:11:11.341099 GW bitfinex WS Info {"event":"info","version":2}
17:11:11.494562 GW bitfinex WS Streaming channel 292368:"trades"
17:11:11.495177 GW bitfinex Changed quoting state to Enabled.
17:11:11.495387 GW bitfinex WS Streaming wallet and orders "OK" 0:"auth"
17:11:12.119728 GW bitfinex WS Streaming channel 295751:"book"
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
17:11:27.372123 Errrror signal 6 Aborted
/home/camille/K/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0x39)[0x7f5e5a442869]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f5e5c8034b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f5e5c803428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f5e5c80502a]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x7f5e5d3650ad]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f066)[0x7f5e5d363066]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f0b1)[0x7f5e5d3630b1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f2c9)[0x7f5e5d3632c9]
/home/camille/K/app/server/lib/K.linux.57.node(_ZN8nlohmann6detail20get_arithmetic_valueINS_10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEEEdLi0EEEvRKT_RT0_+0xac)[0x7f5e5a4523ac]
/home/camille/K/app/server/lib/K.linux.57.node(_ZN1K2QE13quotesAreSameB5cxx11EddbNS_5mSideE+0x274)[0x7f5e5a459ee4]

Please, copy and paste this error into a github issue.
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new
17:11:27.373519 GW bitfinex Attempting to cancel all open orders, please wait..
Aborted

I guess it can be linked to the previous post!

Sorry for sending too much issues today!

**Comment by ctubio** [comment] 2017-08-30 17:28
i belive this was already fixed in latest commits but i was not able to reproduce it yet

**Closed by ctubio** 2017-08-30 17:28 UTC
Labels: non reproducible bug
