### ISSUE TITLE
program crashed--see screenshot

### ISSUE THREAD

**Issue by tyfzheng** [ctubio/Krypto-trading-bot#247] opened 2017-09-23 05:47 UTC
![image](https://user-images.githubusercontent.com/32116214/30770527-dfcbc27e-9ff8-11e7-9f79-059e97f5fe5b.png)

**Comment by ctubio** [comment] 2017-09-23 10:53
umf, yesterday night seems i didnt fix properly the issue

**Comment by ctubio** [comment] 2017-09-23 13:04
im not able to reproduce this issue on Bitfinex anymore, must be fixed on latest commit, dod you reinstall?

**Closed by ctubio** 2017-09-23 13:04 UTC
Labels: fixme!
