### ISSUE TITLE
Errrror: Signal 6 Aborted when running with poloniex config

### ISSUE THREAD

**Issue by gMare** [ctubio/Krypto-trading-bot#235] opened 2017-09-20 17:59 UTC
Yesterday I've posted an issue regarding poloniex (#233) and I've updated to the latest commit. Now I get this message when trying to run with a poloniex config:

```
Errrror: Signal 6 Aborted (Three-Headed Monkey found).
./app/server/K(_ZN1K2EV6reportEv+0x15)[0x55e821c33d15]
./app/server/K(_ZN1K2EV3wtfEi+0x399)[0x55e821c341d9]
/lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7fe4e5dd14b0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fe4e5dd1428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fe4e5dd302a]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0xed)[0x55e82203fd7d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6)[0x55e821fb8076]
./app/server/K(+0x4de0c1)[0x55e821fb80c1]
./app/server/K(+0x56097e)[0x55e82203a97e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7fe4e616d6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fe4e5ea33dd]
```

**Comment by streetbits** [comment] 2017-09-23 00:12
this problem is with all exchanges, not just poloniex

**Comment by ctubio** [comment] 2017-09-23 05:01
im not able to reproduce it in other exchanges like hitbtc/bitfinex/coinbase/okcoin works; when this happens for you? right after on boot oor maybe is after a while?
thanks'

**Comment by ctubio** [comment] 2017-09-29 19:40
someday poloniex will be fixed at https://github.com/ctubio/Krypto-trading-bot/issues/258

**Closed by ctubio** 2017-09-29 19:40 UTC
Labels: fixme!
