### ISSUE TITLE
Little confused on setup

### ISSUE THREAD

**Issue by Nickfost** [ctubio/Krypto-trading-bot#766] opened 2018-07-22 17:52 UTC
I filled out the thing on Earn.com
[I paid the the BTC ](https://www.blockchain.com/en/btc/tx/e889629ceac740cc8812f311a1f8e7f850f3ca47ebe938e666d40aba50d2411a)
I changed my polo API key while troubleshooting and now it wants me to pay again. 

The bot has been giving me this error 

> x 17:48:37.877424 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:41.032452 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:44.293931 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:47.456973 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:50.637565 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:53.769982 GW POLONIEX Nonce must be greater than 1532281733704. You provided 1532281733701..
> x 17:48:53.841719 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:48:56.996038 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:02.278065 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:03.444269 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:06.614651 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:09.859773 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:09.859991 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:13.040531 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:16.215626 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:19.399547 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:22.550052 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:25.707561 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:25.881486 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:29.078587 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:32.301442 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:35.594901 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:38.769466 PG Warrrrning: Unable to calculate TBP, missing wallet data.                                                                                                                                                          lqqk
> x 17:49:41.942901 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:42.968340 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:45.214636 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:48.380114 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:51.555576 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:54.693580 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:57.926810 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:49:58.086594 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:01.239919 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:04.454195 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:07.775948 PG Warrrrning: Unable to calculate TBP, missing wallet data.                                                                                                                                                          mqqj
> x 17:50:10.963637 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:14.318136 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:15.134111 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:17.252577 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:20.373948 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:23.535387 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:26.680144 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:29.813942 GW POLONIEX Nonce must be greater than 1532281829738. You provided 1532281829734..
> x 17:50:29.862300 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:33.036746 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:36.211557 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:39.382285 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:42.607372 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:45.813623 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:45.831524 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:49.135742 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:52.336730 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:55.561435 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:50:58.732705 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:51:01.952351 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:51:02.003635 PG Warrrrning: Unable to calculate TBP, missing wallet data.
> x 17:51:05.149935 PG Warrrrning: Unable to calculate TBP, missing wallet data.

I've messaged you on discord. I would really appreciate the help.

**Comment by ctubio** [comment] 2018-07-22 18:43
seems you changed the api key and that locks again the bot, feel free to let me know the first 5 digits of your new api key and i will unlock it.

it says in the readme that chaning the api key locks the bot again, and it says also that i dont use discord (sorry)

**Comment by ctubio** [comment] 2018-07-22 18:45
let me close this issue as is not a bug

feel free to paste the 5 digits of your new api key here or ina private message on IRC

**Closed** 2018-07-22 18:45 UTC
Labels: question

**Comment by Nickfost** [comment] 2018-07-22 18:52
i was getting this error before and after the key change 
Warrrrning: Unable to calculate TBP, missing wallet data.

**Comment by ctubio** [comment] 2018-07-22 18:57
this error is common to all exchanges when wallet data cannot be read from the exchange
