### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by marcosybarraa** [ctubio/Krypto-trading-bot#1063] opened 2021-02-18 14:09 UTC
Hello,
I paste the last portion of the console error, tried in macOS and Windows 10 with last available Docker versions.

`List of installed K binaries:
-rwxr-xr-x 1 root root 7.0M Feb 18 13:49 /usr/local/bin/K-hello-world
-rwxr-xr-x 1 root root 8.6M Feb 18 13:49 /usr/local/bin/K-trading-bot

NEW CONFIG FILE created at:
-rwxr-xr-x 1 root root 5.7K Feb 18 13:49 K.sh

sed: -e expression #1, char 11: missing command
make: *** [Makefile:235: docker] Error 1`

Thanks in advance

**Comment by ctubio** [comment] 2021-02-18 14:14
morning'''
is possible to see the steps that provoked this output?
(im not able to reproduce it unless i do the same steps)

**Comment by marcosybarraa** [comment] 2021-02-18 14:32
Hi @ctubio , thanks for your reply:
What I did:
  Copied the example in a "Dockerfile" file.
  Executed "docker build --no-cache -t ksh ."  in a terminal in MacOS and in CMD in windows.
* Tried also adding my ENV variables from coinbase PRO, same result.

Trace from Windows 10:

\Desktop\krypto>docker build --no-cache -t ksh .
[+] Building 75.9s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.2s
 => => transferring dockerfile: 787B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/overlordq/8-buster:latest                                               3.1s
 => [1/5] FROM docker.io/overlordq/8-buster@sha256:0d1b1804bdbf6beee6525346c51ad19cad7911ea20b4e532adab70df2efb8  39.4s
 => => resolve docker.io/overlordq/8-buster@sha256:0d1b1804bdbf6beee6525346c51ad19cad7911ea20b4e532adab70df2efb87  0.0s
 => => sha256:0d1b1804bdbf6beee6525346c51ad19cad7911ea20b4e532adab70df2efb8780 2.01kB / 2.01kB                     0.0s
 => => sha256:bac5159b230a9f6ac8aedbb940e99daf2f02c4f92812d766769e555262fbc162 49.21MB / 49.21MB                  13.4s
 => => sha256:e6dcb6f1e458a3233a57c16febe4a40e3ae5780b74b94a52bafc9e262933ad85 7.40MB / 7.40MB                     3.0s
 => => sha256:a38df35355b734c6068bc54bfedc04195e3bb3d4f5236a3bc903343dc72e9fcf 9.78MB / 9.78MB                     3.7s
 => => sha256:53a62890a534f8f84793c0d127a7a1a30f8f9f46ba6684700b27c3a6bbabef9c 7.21kB / 7.21kB                     0.0s
 => => sha256:aa1bfad11c9354aad12ce776ee00dced08456611730c5731532adbc87e3f1683 50.62MB / 50.62MB                  15.8s
 => => sha256:bc590e1ec67b12e3ebfa1d48d23ed0774531db4b1010090a823f2a5c363423e4 180.71MB / 180.71MB                26.7s
 => => sha256:be9d978a1ea92b40d9526afe8717a008cdacc589c539196f887ab426cb2e02c4 4.36kB / 4.36kB                    14.2s
 => => extracting sha256:bac5159b230a9f6ac8aedbb940e99daf2f02c4f92812d766769e555262fbc162                          4.8s
 => => sha256:5d0e76dd119c4e6902436731678f285e67090cfbf93a864243ae08a56a348157 17.75MB / 17.75MB                  17.6s
 => => sha256:9668318b2fe3bcbc7a97965903d7039a77d2b4c53e5fd48ba6d9cecfe8461634 1.31MB / 1.31MB                    16.3s
 => => extracting sha256:e6dcb6f1e458a3233a57c16febe4a40e3ae5780b74b94a52bafc9e262933ad85                          0.6s
 => => extracting sha256:a38df35355b734c6068bc54bfedc04195e3bb3d4f5236a3bc903343dc72e9fcf                          0.6s
 => => extracting sha256:aa1bfad11c9354aad12ce776ee00dced08456611730c5731532adbc87e3f1683                          5.1s
 => => extracting sha256:bc590e1ec67b12e3ebfa1d48d23ed0774531db4b1010090a823f2a5c363423e4                         10.0s
 => => extracting sha256:be9d978a1ea92b40d9526afe8717a008cdacc589c539196f887ab426cb2e02c4                          0.1s
 => => extracting sha256:5d0e76dd119c4e6902436731678f285e67090cfbf93a864243ae08a56a348157                          1.6s
 => => extracting sha256:9668318b2fe3bcbc7a97965903d7039a77d2b4c53e5fd48ba6d9cecfe8461634                          0.1s
 => [2/5] RUN apt-get update  && apt-get install --no-install-recommends -y git sudo                              26.2s
 => [3/5] RUN git clone -b master https://github.com/ctubio/Krypto-trading-bot.git /K                              3.6s
 => [4/5] WORKDIR /K                                                                                               0.1s
 => ERROR [5/5] RUN make docker && rm -rf /var/lib/apt/lists/                                                      3.3s
------
 > [5/5] RUN make docker && rm -rf /var/lib/apt/lists/:
#8 0.474 curl -L https://github.com/ctubio/Krypto-trading-bot/releases/download/0.6.x/K-0.6.0.60-linux-x86_64.tar.gz | tar xz
#8 0.483   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#8 0.483                                  Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0   2753      0 --:--:-- --:--:-- --:--:--  2753
100 9218k  100 9218k    0     0  3943k      0  0:00:02  0:00:02 --:--:-- 7404k
#8 2.897 Checking if sudo           is allowed  at /usr/local/bin.. OK
#8 2.899 Checking if /usr/local/bin is already  in your PATH..      OK
#8 2.901
#8 2.901 List of installed K binaries:
#8 2.933 -rwxr-xr-x 1 root root 7.0M Feb 18 14:06 /usr/local/bin/K-hello-world
#8 2.933 -rwxr-xr-x 1 root root 8.6M Feb 18 14:06 /usr/local/bin/K-trading-bot
#8 2.934
#8 3.138
#8 3.138 NEW CONFIG FILE created at:
#8 3.139 -rwxr-xr-x 1 root root 5.7K Feb 18 14:06 K.sh
#8 3.139
#8 3.145 sed: -e expression #1, char 11: missing command
#8 3.145 make: *** [Makefile:235: docker] Error 1

**Comment by ctubio** [comment] 2021-02-18 15:00
im sorry my bad i see the issue, will be fixed on next commit

:koala: many thanks for your report'''

**Comment by marcosybarraa** [comment] 2021-02-18 16:00
You are welcome, thanks

**Closed** 2021-02-18 18:57 UTC
Labels: :fire: fixme!, :heavy_check_mark: acknowledged
