### ISSUE TITLE
GDAX/Coinbase Extreme CPU Usage

### ISSUE THREAD

**Issue by Zachar543** [ctubio/Krypto-trading-bot#553] opened 2018-01-10 02:10 UTC
I've been running a bot on both GDAX (BTC/USD) and HitBTC for a few months, but as of the last 1-2 months, the GDAX bot has started consuming 100% of the system's CPU, but the HitBTC bot never uses more than 10%.

I've done a bit of tinkering and none of the following have helped:
- Fresh API keys for both exchanges
- Tried including/not including "--naked"
- A fresh install of the bot on Ubuntu and CentOS 7
- A fresh install of the OS
- Multiple identically sized VMs in various Google Cloud regions

All of these result in the GDAX bot maxing out a core of the CPU while the HitBTC bot never goes above 15% of one core (same machine size and region on Google Cloud).

Both test bots' setup:
- Up to date (last 1 hour or so) install
- Google Cloud f1-micro (1 vCPU, 0.6 GB memory, SSD storage)
- Both trading BTC/USD
- Tested using non-unlocked bots (without --free-version)

**Comment by ctubio** [comment] 2018-01-10 02:33
im not able to reproduce this yet; does it goes to 100% at the very begin or takes some time/hours?
also does the used ram go crazy too or is under 30Mb all the time?

thanks for the info :S

**Comment by Zachar543** [comment] 2018-01-10 22:59
From what I am seeing, the CPU used by the bot shoots up to 100% within seconds of the connection to GDAX on startup and the memory is hovering around 40 MB.

Using `--debug`, the following floods the console:
```22:54:05.007934 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.007994 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.014866 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.014907 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.022553 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.022592 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.022618 DEBUG EV void K::QE::timer_1s().
22:54:05.037326 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.037379 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.245294 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.245351 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.253391 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.253428 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.265043 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.265084 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.275844 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.275894 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.282503 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.282536 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.495177 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.495236 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.502118 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.502155 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.502296 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
22:54:05.508546 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.508593 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.521380 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.521427 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.521482 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
22:54:05.527644 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.527685 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.538201 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.538240 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.538308 DEBUG EV K::MG::waitData()::<lambda(K::mTrade)>.
22:54:05.743281 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.743336 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.753995 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.754034 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.764435 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.764476 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.776499 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.776553 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:05.789502 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:05.789554 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.002422 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.002476 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.016904 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.016959 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.031475 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.031527 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.246640 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.246692 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.246728 DEBUG EV void K::QE::timer_1s().
22:54:06.254104 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.254141 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.269707 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.269748 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.275926 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.275962 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.287257 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.287303 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.490334 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.490385 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.500896 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.500942 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.513598 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.513651 DEBUG EV K::QE::waitData()::<lambda()>.
22:54:06.529464 DEBUG EV K::MG::waitData()::<lambda(K::mLevels)>.
22:54:06.529516 DEBUG EV K::QE::waitData()::<lambda()>.
```

Anything else I can provide or that would be helpful?

**Comment by Bomper** [comment] 2018-01-11 09:53
Amazing how [GDAX can't get their act together](https://github.com/coinbase/gdax-node/issues/106), despite [Coinbase receiving millions in funding](https://github.com/coinbase/gdax-node/issues/133).

**Comment by ctubio** [comment] 2018-01-11 12:40
@Bomper you are right but gdax does not care about client code; they just provide a good working server; clients are community maintained (and the node client is the worst ever)

**Comment by ctubio** [comment] 2018-01-11 12:45
@Zachar543 thanks for the logs; one reason of high cpu (but 80% not 100%) is using --free-version; you are totally sure --free-version is not in your config file?

i know is stupid question, but i had attempted hard to reproduce it and i need to totally discard this before keep attempting to reproduce it

**Comment by Zachar543** [comment] 2018-01-11 13:13
@ctubio No problem, I get the need to make sure. Thanks for trying to figure this out. Here's my entire K.sh (without sensitive data):
```
#!/usr/bin/env sh
#  █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
#  ▓ ████ ███ Usage? use current filename of THIS file: █
#  ▒ ████ ███    $ ./K.sh --help                        █
#    ▓███▀█▄  !Feel free to copy/rename/edit THIS file. █
#  ▒ ▒▓██ ███ !Feel free to uncomment any examples, but █
#  ▓ ░▒▓█ ███  do not define multiple times a variable. █
#  █ configurable! executable! K.sh initialization file █
#  █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▀▄▄██▄▌ ▌▐ ▐▄██▄▄▀▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
#  █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▄▀▀▀▀▀▌▄  ▄▐▀▀▀▀▀▄▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
#  █▌ Today, is a beautiful day.▐▌.btw, on THIS file.. ▐█
#  ██   I. Define hardcoded optional K argumentss. F F ██
#  ██  II. Define initial mandatory UI argumentss. E R ██
#  ██ III. Define initial mandatory API arguments. E E ██
#  ██  IV. Execute K loop until CTRL+C or kill -9. L E ██
#  ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄.▄!▄!▄██
#  ▌___                                                 .
#  ▌ I ▐________________________________________________.
#  ▌¯¯¯                                                 .
#  █ OPTIONAL_ARGUMENTS                                 .
#  ██ - Allows a list of arguments, to avoid write it always in the command-line.
OPTIONAL_ARGUMENTS="--naked"
#OPTIONAL_ARGUMENTS="--autobot --naked"
#  ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
#  ▌____                                                .
#  ▌ II ▐_______________________________________________.
#  ▌¯¯¯¯                                                .
#  █ UI_USERNAME                                        .
#  ██ - Allows any username, to authenticate UI connections.
#UI_USERNAME=1234abcd
UI_USERNAME=<removed>
#  ▌____________________________________________________.
#  █ UI_PASSWORD                                        .
#  ██ - Allows any password, to authenticate UI connections.
#UI_PASSWORD=efgh5678
UI_PASSWORD=<removed>
#  ▌____________________________________________________.
#  █ UI_OPENPORT                                        .
#  ██ - Allows any port number, to listen to UI connections.
#UI_OPENPORT=6969
UI_OPENPORT=<removed>
#  ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
#  ▌_____                                               .
#  ▌ III ▐______________________________________________.
#  ▌¯¯¯¯¯                                               .
#  █ API_EXCHANGE                                       .
#  ██ - Allows one of the following exchange names (or leave NULL for test mode):
API_EXCHANGE=COINBASE
#API_EXCHANGE=BITFINEX
#API_EXCHANGE=BITFINEX_MARGIN
#API_EXCHANGE=HITBTC
#API_EXCHANGE=OKCOIN
#API_EXCHANGE=OKEX
#API_EXCHANGE=KRAKEN
#API_EXCHANGE=KORBIT
#API_EXCHANGE=POLONIEX
#API_EXCHANGE=NULL
#  ▌____________________________________________________.
#  █ API_CURRENCY                                       .
#  ██ - Allows any existent currency pair (see the website of the exchange), the format must be "AAA/ZZZ".
#API_CURRENCY=BTC/EUR
API_CURRENCY=BTC/USD
#  ▌____________________________________________________.
#  █ API_KEY                                            .
#  ██ - Allows any valid API KEY (see the website of the exchange).
#  ██ - All exchanges must have API KEY.
API_KEY=<removed>
#API_KEY=NULL
#  ▌____________________________________________________.
#  █ API_SECRET                                         .
#  ██ - Allows any valid API SECRET (see the website of the exchange).
#  ██ - All exchanges must have API SECRET.
API_SECRET=<removed>
#API_SECRET=NULL
#  ▌____________________________________________________.
#  █ API_PASSPHRASE                                     .
#  ██ - Allows any valid API PASSPHRASE (see the website of the exchange).
#  ██ - Only COINBASE and KORBIT exchanges must have API PASSPHRASE, other exchanges can be NULL.
API_PASSPHRASE=<removed>
#API_PASSPHRASE=NULL
#  ▌____________________________________________________.
#  █ API_USERNAME                                       .
#  ██ - Allows any valid API USERNAME (see the website of the exchange).
#  ██ - Only KORBIT exchange must have API USERNAME, other exchanges can be NULL.
#API_USERNAME=exampleapiusername
API_USERNAME=NULL
#  ▌____________________________________________________.
#  █ API_HTTP_ENDPOINT                                  .
#  ██ - Allows one of the following urls (see the website of the exchange).
#  ██ - All exchanges must have API_HTTP_ENDPOINT.
API_HTTP_ENDPOINT=https://api.gdax.com
#API_HTTP_ENDPOINT=https://api.bitfinex.com/v1
#API_HTTP_ENDPOINT=https://api.hitbtc.com/api/2
#API_HTTP_ENDPOINT=https://www.okcoin.com/api/v1/
#API_HTTP_ENDPOINT=https://www.okcoin.cn/api/v1/
#API_HTTP_ENDPOINT=https://www.okex.com/api/v1/
#API_HTTP_ENDPOINT=https://api.kraken.com
#API_HTTP_ENDPOINT=https://api.korbit.co.kr/v1
#API_HTTP_ENDPOINT=https://poloniex.com
#API_HTTP_ENDPOINT=NULL
#  ▌____________________________________________________.
#  █ API_WSS_ENDPOINT                                   .
#  ██ - Allows one of the following urls (see the website of the exchange).
#  ██ - Almost all exchanges must have API_WSS_ENDPOINT, only KRAKEN and KORBIT exchanges can be NULL.
API_WSS_ENDPOINT=wss://ws-feed.gdax.com
#API_WSS_ENDPOINT=wss://api.bitfinex.com/ws/2
#API_WSS_ENDPOINT=wss://api.hitbtc.com/api/2/ws
#API_WSS_ENDPOINT=wss://real.okcoin.com:10440/websocket/okcoinapi
#API_WSS_ENDPOINT=wss://real.okcoin.cn:10440/websocket/okcoinapi
#API_WSS_ENDPOINT=wss://real.okex.com:10441/websocket
#API_WSS_ENDPOINT=wss://api.poloniex.com
#API_WSS_ENDPOINT=NULL
#  ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
#  ▌____                                                .
#  ▌ IV ▐______________________________________________ .
#  ▌¯¯¯¯                                                .
until `#valgrind` `#gdb --args` ./app/server/K          \
    --title      ${0##*/}                               \
    --port       $UI_OPENPORT                           \
    --user       $UI_USERNAME                           \
    --pass       $UI_PASSWORD                           \
    --exchange   $API_EXCHANGE                          \
    --currency   $API_CURRENCY                          \
    --apikey     $API_KEY                               \
    --secret     $API_SECRET                            \
    --passphrase $API_PASSPHRASE                        \
    --username   $API_USERNAME                          \
    --http       $API_HTTP_ENDPOINT                     \
    --wss        $API_WSS_ENDPOINT                      \
                 $OPTIONAL_ARGUMENTS "$@"           ;   #
  do                                                # K #
    echo K crashed with exit code $?.. Respawning.. ;   #
    sleep 3                                         ;   #
done                                                ;   #
#  ██▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄;▄:wq
```

I have a few things I want to try still, but I'll try these a bit later today:
- I run the bot as a non-root user that has passworded-sudo access. It may be worth testing a root vs non-root user.
- Though my main GDAX bot had USD available to the bot and had this issue, these last several test were run when my account balances were empty.

**Comment by ctubio** [comment] 2018-01-11 13:18
many thanks for the info'' (just saying, i had never run it with root)

**Comment by ctubio** [comment] 2018-01-11 13:30
maybe stunnel is stucked? try `killall stunnel` before run it :S

**Comment by Zachar543** [comment] 2018-01-11 17:10
After each of the tests, I've been shutting down the VM entirely. So, stunnel was not running from the last test.

Interestingly, changing to ETH/BTC seems to fix this entirely (I only tested for a few minutes), and the CPU usage of the bot stays well below 10%.

Could it be volume/websocket throughput related? ETH/BTC is significantly less active than BTC/USD on GDAX.

**Comment by ctubio** [comment] 2018-01-12 12:47
im not able to test BTC/USD but im on BTC/EUR; in eur we have between 3000 and 4000 market levels on each side; gdax sends all on boot, and later increments the modifications 1 by 1.

i dont see any issues with 4000 market levels, but i donno how many there are on BTC/USD

can you see in the footer of the UI the amount of market levels on each side?
just for curiosity i think, cos looking at the logs seems `EV K::MG::waitData()::<lambda(K::mLevels)>` runs fast as expected (so seems not wasting computation cycles)

**Comment by Zachar543** [comment] 2018-01-12 23:30
Using `--free-version`, I see 10265 bid and 17452 ask levels.

When the CPU usage of the bot is at 100% (for this test setup, that maxes out the whole VM), the UI is still usable, but saving and enabling/disabling the bot takes a few seconds.

**Comment by ctubio** [comment] 2018-01-15 00:27
maybe `--market-limit=500` helps to avoid the high cpu? if so i will need to rethink the market data parser :S

**Comment by Zachar543** [comment] 2018-01-16 01:23
It looks like `--free-version --market-limit=500` causes the bot to see `500|500`, but the 100% CPU usage remains.

Anything else I can try to help narrow down the issue?

**Comment by ctubio** [comment] 2018-01-18 03:14
no idea how to reproduce or narrow down yet

**Comment by ctubio** [comment] 2018-01-23 03:08
im still trying hard to reproduce it; meanwhile i have no luck, im moving all sync calls to async in the hope that is because some double called slow function

**Comment by werkkrew** [comment] 2018-01-24 00:48
I am having the same issue.  I have done a lot of troubleshooting with strace, lsof, and various debug flags and I can't seem to figure it out.

I have also observed that this does not happen on "slower" pairs on GDAX but is definitely a problem on BTC/USD.

To add, it seems like not only is the CPU pegged at 100% but after a few minutes the orderbook gets way out of sync with reality.  For example the top bid/ask levels can be hundreds of dollars away from the actual orderbook.

If it helps I am running Arch Linux x64 on a Linode VPS with 2x vCPU/4gb memory/ssd storage.

**Comment by ctubio** [comment] 2018-01-24 20:15
ima try limiting the market levels to 321, anyway i think it doesnt makes sense to have 17000 market levels

**Comment by ctubio** [comment] 2018-01-26 18:48
ima close this but feel free to open a new issue if your gdax bots eat al cpu anytime

**Closed by ctubio** 2018-01-26 18:48 UTC
Labels: fixme!

**Comment by rettori** [comment] 2018-02-05 18:55
Also seeing 100% CPU on Gdax/ETH/USD 321|321
