### ISSUE TITLE
Raspberry Bitfinex: Bot cannot cancel orders from Orderbook?

### ISSUE THREAD

**Issue by zmbbmz** [ctubio/Krypto-trading-bot#527] opened 2017-12-31 16:07 UTC
It seems that the bot cannot cancel orders from the order book. It tries to place f.e. new buy orders, but cannot delete the old (in a bull run) and vice versa. In the BF webui, there are error messages like "cannot find order" and "cannot place buy order xxxxxx, not enough funds" (because the funds are locked in old orders).

also the checkbox "clx?" should do a order book reset after 5min, as if im understand that correctly?
actually it does not.

does anybody have the same behaviors?
the api key has all necessary rights, though.

greetz zmb

**Comment by ctubio** [comment] 2017-12-31 16:18
it works fine bitfinex as of today here; can you share some `--debug` lines?
thanks''

**Comment by ctubio** [comment] 2017-12-31 16:41
closing cos i can really not reproduce this issue, but please feel free to share your `--debug` logs here if you still are facing this

**Comment by zmbbmz** [comment] 2017-12-31 17:19
Hi! Thx for the quick answer. i will do that and make screenshots of it. hold on...

**Comment by zmbbmz** [comment] 2018-01-01 19:33
![bf_1](https://user-images.githubusercontent.com/34986109/34470502-c1b48292-ef32-11e7-9af2-a07e16894f7e.jpg)
![bf_2](https://user-images.githubusercontent.com/34986109/34470503-c5806cce-ef32-11e7-81c6-d0cc290af769.jpg)

I uploaded 2 screenshots with error messages in bitfinex UI. There you can see, that the bot cannot update/cancel orders. the old ones remains in the order book.

**Comment by zmbbmz** [comment] 2018-01-01 20:18
[debug.txt](https://github.com/ctubio/Krypto-trading-bot/files/1596349/debug.txt)

**Comment by ctubio** [comment] 2018-01-01 22:35
ok many thanks, lines like the following looks suspicious:
```
20:04:02.795336 DEBUG OG cancel BID id 66708133::-1849035180.
```

will investigate soOn'' many thanks for the report''

**Comment by ctubio** [comment] 2018-01-01 23:47
for me all orders at SNT/USD have correct cancel ids., can you share your `$ uname -a` ?

thanks''

**Comment by ctubio** [comment] 2018-01-02 00:01
mm.. i see it happens each 5min, must be because of `cxl`; meanwhile is not fixed, disabling `cxl` may help you

**Comment by zmbbmz** [comment] 2018-01-02 08:48
yes, with btc/usd, xrp/usd  and snt/usd so far. all have the similar problem with not canceling orders. maybe the msg "order not found" from the web ui give us a hint. 

clx? have no effect, as i can say, he dont cancel anything after 5min. additionally the bot should cancel all orders, when you manually stop him, but nothing happens, too

**Comment by zmbbmz** [comment] 2018-01-02 10:11
ok, so after some research, maybe the problem could be only 1gig ram / raspberry pi 3.
i give you some feedback, after setting up an fresh icore5 / 8gb ram / clean ubuntu in virtualbox on win10.

**Comment by serzhiio** [comment] 2018-01-03 21:10
That is strange but i'm observing same situation on one of my HitBTC instances.

**Comment by ctubio** [comment] 2018-01-04 12:34
i dont think hitbtc have same situation just because hitbtc order ids are not numeric, so they can not have a   negative sign; can you show some --debug-orders of your failing to be canceled hitbtc orders¿

**Comment by ctubio** [comment] 2018-01-04 12:37
@zmbbmz maybe the problem is only in the 32bits version of the raspberry build; i will run my raspberry too soOn

**Comment by zmbbmz** [comment] 2018-01-04 16:02
yepp, running on the new machine works fine.

**Comment by ctubio** [comment] 2018-01-13 03:28
many thanks for the info''

**Comment by 5ymph0en1x** [comment] 2018-01-14 10:31
Hi everyone !
I'm running into the same issue wih my raspberry pi 3...
I think there is something to find here.

**Closed** 2018-01-16 01:16 UTC
Labels: bug, in the lab
