### ISSUE TITLE
Gdax bot stops placing orders

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#220] opened 2017-09-14 11:25 UTC
Hi, after the latest commit some strange situation happen

The vps is based on ubuntu 16.04 and
node is 8.4.0
gcc and c++ are at 7.2.0

The problem is on Gdax and Bitfinex, I use only this for now
On Gdax the UI works but I see one order (that on gdax side don't exist) and the TBP run
![gdax](https://user-images.githubusercontent.com/5203988/30427409-032330c2-9950-11e7-813a-deb462b473e0.PNG)

On Bitfinex, the UI is not connected but the bot sill calculate TBP
![bitfinex](https://user-images.githubusercontent.com/5203988/30427421-13679ef0-9950-11e7-8ec7-71c860418672.PNG)

Than happen at random, maybe some hours maybe some minutes

Is possible to generate more log to see what happen? Maybe I can help in some way.

J

**Comment by ctubio** [comment] 2017-09-14 11:28
moring'''
can you maybe run the application in the foreground with `./K,sh` and see if in the output is there any interesting error message? for me tonight Bitfinex and Coinbase didnt had any problems so im not sure what was yours

**Comment by Jorman** [comment] 2017-09-14 18:53
Hi, I'll try, now I make the latest commit.

Is possible that is all about the TBP? I noticed right now (bot was alive but seem frozen, TBP calculating but nothing)

But I see that
17:44:38.681274 TBP 0% = 0.00000000 BTC
No order made and btc on wallet
I don't know how to make you a better report :(

**Comment by ctubio** [comment] 2017-09-14 19:37
to check if the problem is TBP you can disable it by enabling `%`, and set TBP and pDiv to `50`, then the bot is supopsed to always make orders

**Comment by Jorman** [comment] 2017-09-14 20:16
I'll try tnx.

I'll also try to run in foreground, gdax some time disconnect then reconnect but after a while, freeze

**Comment by Jorman** [comment] 2017-09-14 20:36
Just an update for your on gdax
Just tried, freeze after some minutes, you can see, pdiv at 50% order placed but seems freeze
The screen was made at 22:35, you can see the time for the order and gdax interface
![now](https://user-images.githubusercontent.com/5203988/30454614-2ea07348-999d-11e7-8466-94c9b3b2f4f9.PNG)

Any idea?

**Comment by ctubio** [comment] 2017-09-15 00:03
`KCONFIG=X make stop` to stop only X.json

do you have apMode to Manual? otherwise TBP will be still automaticaly calculated

**Comment by ctubio** [comment] 2017-09-15 01:03
i was able to reproduce it on gdax; bitfinex still works great for me

**Comment by Jorman** [comment] 2017-09-15 06:24
Hi, good to know
On bitfinex is about the same, I can't success to run to 24h the bot without any freeze/disconnection

There's an option to start K like in debug mode for example
KCONFIG=X make start --debug

And see all the relevant operation to see where the bot stop?

**Comment by ctubio** [comment] 2017-09-15 11:55
no `--debug` yet, but is a nice idea, will consider, thanks'¡

**Comment by ctubio** [comment] 2017-09-18 00:44
if you agree lets close this and fix it at https://github.com/ctubio/Krypto-trading-bot/issues/217

**Closed by ctubio** 2017-09-18 00:44 UTC
Labels: acknowledged, bug

**Comment by Jorman** [comment] 2017-09-18 19:59
Tnx!
Btw, how to use the --debug-quotes and --debug-orders?

I tried with
KCONFIG=gdax-btc-eur-3000 ARGUMENTS="--colors --debug-quotes --debug-orders" make start
But nothing on console
I also tried with
KCONFIG=gdax-btc-eur-3000 --debug-orders make start
or
KCONFIG=gdax-btc-eur-3000 make start --debug-orders
but don't start
