### ISSUE TITLE
Binance error

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#1121] opened 2021-08-15 11:10 UTC
Hi,

Im facing errors at Binance again:

08/15 11:05:05.848043 GW BINANCE WS streaming [levels|trades|orders|wallet].
08/15 11:05:05.848121 GW BINANCE Quoting state changed to CONNECTED.
08/15 11:05:05.852768 GW BINANCE WS ignored msg: {"error":{"code":2,"msg":"Inval                                                                                        id request: invalid stream"},"id":2}.
08/15 11:05:06.766448 GW BINANCE WS Disconnected, reconnecting in 7s..
08/15 11:05:06.766549 GW BINANCE Quoting state changed to DISCONNECTED.

**Comment by ctubio** [comment] 2021-09-05 03:56
im nto able to reproduce this error but the only stream that can be invalid is the only stream that is variable.

the only stream variable is the one fetched at /api/v3/userDataStream endpoint.

soo.. if you can't fetch your user stream, the only reason i can imagine is because its ratelimited or banned

we cannot fix this error once it happens, but we can avoid it to happen, with a bit of luck, at https://github.com/ctubio/Krypto-trading-bot/issues/1118

:koala: if you agree lemme close this issue and fix the known binance errors in the other issue

**Closed by ctubio** 2021-09-05 03:56 UTC
Labels: :loudspeaker: question
