### ISSUE TITLE
GDAX macOS doesn't work

### ISSUE THREAD

**Issue by wulabs** [ctubio/Krypto-trading-bot#136] opened 2017-08-13 06:42 UTC
I have updated to latest code from today, commit 76223abc19391e4e2d0cb5318a2785bd6fa8d35d. Now seems to error out for me on both Coinbase and OKCoin.  It was working before, with code from July 21st.  See below error. Is there a way to get more descriptive error logging? I am running OSX 10.12.3. Compiler info below.

`
$ ./node_modules/.bin/forever K.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
K.darwin.57
6:35:49.492864 CF settings loaded from JSON file K OK.
6:35:49.495266 UI ready over HTTPS on external port 3000.
6:35:49.496468 GW okcoin allows client IP.
6:35:49.496523 GW okcoin:
- autoBot: no
- pair: btc_usd
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
error: Forever detected script was killed by signal: SIGSEGV
`

`
g++ -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
`

**Comment by ctubio** [comment] 2017-08-13 15:11
consider using Debian or checkout an old commit; currently macOS is broken

**Comment by ctubio** [comment] 2017-08-14 03:59
in case https://github.com/ctubio/Krypto-trading-bot/issues/133 is ever resolved i will try to apply the same solution here

**Comment by d1gits** [comment] 2017-08-29 13:50
What alternative do you want to use for node? Maybe I can help out.

**Comment by ctubio** [comment] 2017-08-29 19:10
just plain c++

**Comment by jokester01au** [comment] 2017-12-11 10:52
I'm on mac. I can try to help with this. Have you looked at it any further?

**Comment by ctubio** [comment] 2017-12-16 18:16
not yet but starts to be the time to retry it; since latests commit theres just a single thread again and hopefully compiling in mac should not end up in a broken app with mangled scopes

**Comment by shri046** [comment] 2017-12-20 23:52
I am having issues getting things working on OSx too, at this point is it an issue with compiling/installing overall or just that WebUI doesn't work?

I am able to run `make packages` without any issues but `make dist && make` always end up with issues.

**Comment by ctubio** [comment] 2017-12-21 03:45
yea (im sorry) that is expected as of today; make packages is the only piece of code that survived the migration; all other is known to fail on mac; i will try soOn but im lazy and always prospone because i know i will not make use of it since mac is for user apps not for servers apps (if you ask me)

**Comment by shri046** [comment] 2017-12-29 14:19
Understood but right now I only have a Mac to play with the code. I have another machine running Redhat and the code does not build there too. The only option left for me is to use Docker which in itself is causing problems (I am new to Docker so it might be just me not setting things up right).

Having said that I got the Makefile updated to the point where `make dist` now works. But when I run `make` after that, I keep getting an error saying 'no input files'. So question really is that to build everything from source code is `make dist && make` sufficient?

Apologize for making this more of a discussion thread but I couldn't find any developer docs that list out the steps.

**Comment by ctubio** [comment] 2017-12-30 06:31
epoll does not exits on mac, is mandatory to replace epoll with libuv (only for mac)

**Comment by ctubio** [comment] 2017-12-31 05:42
now aalmost works but the linker paths are wrong, end users require to set DYLD_LIBRARY_PATH to make the whole thingy work :( will try to avoid it someday

**Comment by ctubio** [comment] 2018-01-01 00:43
@shanejonas to build on a new machine i do `make dist K bundle`

**Comment by ctubio** [comment] 2018-01-01 06:04
it should run under macOS after https://github.com/ctubio/Krypto-trading-bot/commit/a2f98bcf7d45da64e7d2b3f0edcf52602cd18d43

**Comment by shri046** [comment] 2018-01-02 04:37
@ctubio Thanks for the fix! I am now able to run `make install` and launch K.sh but the app errors with a segmentation fault almost immediately.

mac-C02TQG6MHTD6:Krypto-trading-bot shri$ ./K.sh 
K build x86_64-apple-darwin17 2018-01-02 03:21:50.
K version 0day.
04:34:28.429766 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
04:34:28.431685 UI ready over HTTPS on external port 3000.
04:34:28.432208 QP Warrrrning: using default values for Quoting Parameters.
04:34:28.432275 DB loaded 0 historical Trades.
04:34:28.432329 DB loaded 0 STDEV Periods.
04:34:28.432398 DB loaded 0 historical FairValues.
04:34:28.432450 DB loaded 0 historical Profits.
04:34:28.432530 DB loaded TBP = 0.00000000 BTC.
sh: /bin/pidof: No such file or directory
04:34:29.248593 GW COINBASE allows client IP.
04:34:29.248639 GW COINBASE: 
- autoBot: no
- symbols: BTC-USD
- minTick: 0.01000000
- minSize: 0.00010000
- makeFee: 0.00000000
- takeFee: 0.00000000.

04:34:29.867570 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1514867669867
- tracelog: 
0   K                                   0x000000010d441645 _ZN1K2EV3wtfEi + 645
1   ???                                 0x0000000000000001 0x0 + 1

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

04:34:29.867621 GW COINBASE Attempting to cancel all open orders, please wait..
04:34:30.573196 GW COINBASE cancell all open orders OK.
04:34:33.578073 K exit code 1.
K crashed with exit code 1.. Respawning..
K build x86_64-apple-darwin17 2018-01-02 03:21:50.
K version 0day.
04:34:36.946449 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
04:34:36.959847 IU Errrror: Use another UI port number, 3000 seems already in use by:
.

Also I am still not able to run `make dist` after picking up the latest changes. One thing I noticed is the CARCH is now set to darwin17 but the make process reports CARCH as darwin16.6.0 for my machine.

**Comment by ctubio** [comment] 2018-01-03 01:27
mm.. the error seems this `sh: /bin/pidof: No such file or directory` msg; only place where we use pidof is at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/fn.h#L143

i will try to avoid this `pidof` and replace it by some `ps` like at https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/fn.h#L421

**Comment by shri046** [comment] 2018-01-03 01:32
I think there is a quick fix for the pidof issue, brew has a formulae that can be installed and used. The only issue is the Mac version of pidof is under

mac-C02TQG6MHTD6:Krypto-trading-bot shri$ which pidof
/usr/local/bin/pidof

So it is really a matter of either creating a symlink manually or through the Makefile. Personally I think this might best step included in the documentation specifically for Mac users. From what I could tell it is only affecting shutdown of stunnel, not entirely sure if it is the cause for the seg faults.

**Comment by shri046** [comment] 2018-01-03 01:37
Regarding compile, I am able to tweak the Makefile to be able to run `make dist` all the way through. The place where I get stuck is running the `make` command. I run in to the below error on Mac, Ubuntu and Debian

x86_64-linux-gnu-g++: error: build-x86_64-linux-gnu/local/lib/K-x86_64-linux-gnu.a: No such file or directory 

So either `make dist` is still messed up or I am missing a step as I cannot possibly run in to the same error on all three operating systems.

**Comment by ctubio** [comment] 2018-01-03 01:42
please note the file `build-x86_64-linux-gnu/local/lib/K-x86_64-linux-gnu.a` is my private library; it is included in the zips and is provided while running `make install`; it is needed by `make` and `make dist` is not related to it nor uses it (after `make install dist K bundle`)

**Comment by shri046** [comment] 2018-01-03 01:48
@ctubio ahh gotcha, so basically `make install` is a pre-requisite to everything. Without that there is no way to build the source code incremental changes.

The path above was from the Ubuntu instance I was testing. I was under the impression that `make dist && make` is sufficient to get everything built but didn't realize the dependency on the private library file that gets pulled in as part of `make install`.

**Comment by ctubio** [comment] 2018-01-03 01:52
yea you are right; sorry for the confusion :dancer: some day will try to follow better the standards on this first steps

**Comment by shri046** [comment] 2018-01-03 02:21
No worries, just making sure I had my head straight on :)

Also, I tested the pidof issue by creating a symlink to /bin/pidof on my Mac. The pidof error is not present in the logs anymore but the segmentation fault still persists.

mac-C02TQG6MHTD6:Krypto-trading-bot shri$ ./K.sh 
K build x86_64-apple-darwin17 2018-01-02 03:21:50.
K version 0day.
02:05:19.919344 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
02:05:19.920586 UI ready over HTTPS on external port 3000.
02:05:19.920905 QP Warrrrning: using default values for Quoting Parameters.
02:05:19.920947 DB loaded 0 historical Trades.
02:05:19.920980 DB loaded 0 STDEV Periods.
02:05:19.921079 DB loaded 0 historical FairValues.
02:05:19.921118 DB loaded 0 historical Profits.
02:05:19.921168 DB loaded TBP = 0.00000000 BTC.
02:05:20.402995 GW COINBASE allows client IP.
02:05:20.403033 GW COINBASE: 
- autoBot: no
- symbols: BTC-USD
- minTick: 0.01000000
- minSize: 0.00010000
- makeFee: 0.00000000
- takeFee: 0.00000000.

02:05:21.026449 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1514945121026
- tracelog: 
0   K                                   0x000000010fa85645 _ZN1K2EV3wtfEi + 645
1   ???                                 0x0000000000000001 0x0 + 1

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

02:05:21.026481 GW COINBASE Attempting to cancel all open orders, please wait..
02:05:21.631439 GW COINBASE cancell all open orders OK.
02:05:24.636896 K exit code 1.
K crashed with exit code 1.. Respawning..
K build x86_64-apple-darwin17 2018-01-02 03:21:50.
K version 0day.
02:05:27.977704 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
02:05:27.983694 IU Errrror: Use another UI port number, 3000 seems already in use by:
.

Let me know if I can get more information around this error or help in any way I can.

**Comment by ctubio** [comment] 2018-01-03 02:30
maybe can you show some --debug lines? (at that point is supposed that libquickfix is going to be loaded and started, but maybe is another event)

**Comment by shri046** [comment] 2018-01-03 02:38
Adding --debug to optional arguments did not make a difference in the output I think.

mac-C02TQG6MHTD6:Krypto-trading-bot shri$ ./K.sh 
K build x86_64-apple-darwin17 2018-01-03 02:17:40.
K version 0day.
02:35:12.561844 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
02:35:12.563065 UI ready over HTTPS on external port 3000.
02:35:12.563366 QP Warrrrning: using default values for Quoting Parameters.
02:35:12.563409 DB loaded 0 historical Trades.
02:35:12.563441 DB loaded 0 STDEV Periods.
02:35:12.563483 DB loaded 0 historical FairValues.
02:35:12.563509 DB loaded 0 historical Profits.
02:35:12.563549 DB loaded TBP = 0.00000000 BTC.
02:35:13.496898 GW COINBASE allows client IP.
02:35:13.496937 GW COINBASE: 
- autoBot: no
- symbols: BTC-USD
- minTick: 0.01000000
- minSize: 0.00010000
- makeFee: 0.00000000
- takeFee: 0.00000000.

02:35:13.942166 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1514946913942
- tracelog: 
0   K                                   0x0000000106b828f5 _ZN1K2EV3wtfEi + 645
1   ???                                 0x0000000000000001 0x0 + 1

Yikes!
please copy and paste the error above into a new github issue (noworry for duplicates).
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new

02:35:13.942198 GW COINBASE Attempting to cancel all open orders, please wait..
02:35:14.609434 GW COINBASE cancell all open orders OK.
02:35:17.614675 K exit code 1.
K crashed with exit code 1.. Respawning..
K build x86_64-apple-darwin17 2018-01-03 02:17:40.
K version 0day.
02:35:20.979744 DB /data/db/K.COINBASE.BTC.USD.db loaded OK.
02:35:20.985982 IU Errrror: Use another UI port number, 3000 seems already in use by:
.

**Comment by ctubio** [comment] 2018-01-03 02:44
so cruel is the first time i see a silent --debug xD ok i will investigate here too soOn

**Comment by Werewolve** [comment] 2018-01-03 23:26
Any news here? Got the same error:

23:20:36.652048 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: LTC/EUR
- lastbeat: 1515021636651
- tracelog:
0   K                                   0x00000001040c58f5 _ZN1K2EV3wtfEi + 645
1   ???                                 0x0000000111265978 0x0 + 4582693240

**Comment by shri046** [comment] 2018-01-03 23:29
@Werewolve What is the output of `g++ -dumpmachine` on your machine?

**Comment by Werewolve** [comment] 2018-01-03 23:31
@shri046  x86_64-apple-darwin16.7.0

**Comment by shri046** [comment] 2018-01-03 23:34
@Werewolve Okay that is the same version that I am running. This could likely be related to the fact that the lib is built for x86_64-apple-darwin17 and there are compatibility issues. Not quite sure yet but hopefully it will be fixed soon.

**Comment by shri046** [comment] 2018-01-04 00:04
@ctubio So here is some more info, hoping it will help. I tried `make dist` with the brew installed gcc/g++ and couldn't get things working because of dependency/library issues. So I modified the Makefile locally to use clang/LLVM. At this point I got past the dependency errors but ran in to this error

`
build-x86_64-apple-darwin16.7.0/local/include/uWS/Node.h:175:13: error: value of type '__bind<int &, sockaddr *&, unsigned int &>' is not contextually convertible to 'bool'
        if (bind(listenFd, listenAddr->ai_addr, listenAddr->ai_addrlen) || ::listen(listenFd, 512)) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
build-x86_64-apple-darwin16.7.0/local/include/uWS/Node.h:175:73: error: invalid operands to binary expression ('__bind<int &, sockaddr *&, unsigned int &>' and 'int')
        if (bind(listenFd, listenAddr->ai_addr, listenAddr->ai_addrlen) || ::listen(listenFd, 512)) {
`
So I found this [SO post](https://stackoverflow.com/questions/16180322/c-xcode-sockets-bind-error) that suggested the problem is with the line `using namespace std;` in K.cxx. Based on that info I updated Node.h to change qualify bind with ::bind. Running make dist now completed successfully.

This still did not fix make which I believe is due to the private lib being released for darwin17. Is there anyway you can create the lib for 16.6.7? I could try make again to see if it works.

**Comment by commonwealthgoods** [comment] 2018-01-28 04:08
I just installed on OSX and got the following error:

04:04:02.615346 Errrror: Signal 6 Abort trap: 6 (Three-Headed Monkey found):
- upstream: COINBASE
- currency: BTC/USD
- lastbeat: 1517112242615
- os-uname: uname: illegal option -- o
usage: uname [-amnprsv]

- tracelog: 
0   K                                   0x0000000106fb9a78 _ZN1K2EV3wtfEi + 792
1   ???                                 0x0000000000000011 0x0 + 17

**Comment by ctubio** [comment] 2018-02-04 23:58
only gdax fails on macOS, must be because libquickfix..

**Closed** 2018-02-06 01:16 UTC
Labels: acknowledged, bug
