### ISSUE TITLE
--free-version Bot freezing periodically

### ISSUE THREAD

**Issue by woshikie** [ctubio/Krypto-trading-bot#560] opened 2018-01-10 23:55 UTC
Probably cause I'm using --free-version
Can I propose to close all open trades before entering freezing stage? 
PS. If someone could point to me where argFree is used, or the entry point for the freeze, I'd make a pull request myself

**Comment by ctubio** [comment] 2018-01-11 12:52
i dont understand what you mean by "entering freezing stage"; but closing all open trades seems antinatural.

an open trade should only by closed if is calculated a better trade to be placed.

if you agree please explain your problem instead of propose solutions.

**Comment by woshikie** [comment] 2018-01-11 15:38
so, currently, im using --free-version cause i thought, hey i don't really mind giving you some hashes every now and then and getting delayed information from the market doesn't hurt toO much, i hope. But, the bot freezes about every 5-10mins and it lasts for about 5 to 20 minutes. Im not very sure why.

**Comment by ctubio** [comment] 2018-01-11 18:16
nope, that is not intended; should be not freezed, thats why i dont understand the term.

when is freezed, for example, if you click the green/red button it keeps yellow without go to green/red?
oor when is freezed, clicking [Save] button in the settings only says Pending...?

**Comment by woshikie** [comment] 2018-01-12 04:54
both of what you said happens.

**Comment by ctubio** [comment] 2018-01-12 12:22
ook many thanks for the interesting info'' lemme refocus brain there again :dancer:

for now i still have no idea how to reproduce this :(

**Comment by ctubio** [comment] 2018-01-15 00:20
on next commit --free-version will use 69% of cpu instead of 80%; anyway i dont think nothing is resolved; will keep trying to reproduce this

**Comment by woshikie** [comment] 2018-01-15 00:25
My vps running Ubuntu lts 16 isn't giving me any issues, while my desktop and vm running Ubuntu 17 are having the issue

**Comment by ctubio** [comment] 2018-01-15 00:41
thanks for the info''

**Comment by ctubio** [comment] 2018-01-15 03:52
closing cos after trying hard im still not able to reproduce this :(

i will keep testing --free-version but on a debian cos i got the same results as in ubuntu17 or ubuntu16 (the issue doesnt looks like is because ubuntu17)

**Comment by ctubio** [comment] 2018-01-15 13:08
lets keep looking for this somehow

**Comment by woshikie** [comment] 2018-01-15 17:30
i've really only done the bare minimum to setup for my VM
`sudo git clone https://github.com/ctubio/Krypto-trading-bot.git K 
cd K
apt-get install make -y
make install`

**Comment by ctubio** [comment] 2018-01-15 17:58
here i had never prefixed git or make commands with sudo; i use a normal user with sudoers permission

for install may not matter, but when running the app consider to run always from a non-root user

**Comment by ctubio** [comment] 2018-01-16 01:21
can you saw you "$ uname -a" from the machine it crashes?
thanks''

**Comment by woshikie** [comment] 2018-01-16 14:52
i have always been running with sudo. my VPS works ok with it though

**Comment by woshikie** [comment] 2018-01-16 18:51
@ctubio could you maybe, perhaps make the miner to be running on a seperate thread? I suspect that perhaps the ISP in my country have bad connection to the mining pool or that because my CPU isn't really all that powerful, the OS' scheduler schedules for time to the miner instead of the bot.

**Comment by ctubio** [comment] 2018-01-18 01:57
is already using `std::launch::async` from http://www.cplusplus.com/reference/future/launch/

**Comment by ctubio** [comment] 2018-01-18 02:01
ima close this cos i really cannot reproduce it no matter what i do

running with sudo works but is not secure; the app does not need any kind of permissions, so if ever makes use of it is because was compromissed, in that case running it with sudo will for sure allow the attack

**Closed by ctubio** 2018-01-18 02:01 UTC
Labels: fixme!
