### ISSUE TITLE
HitBTC and Bequant Error 500

### ISSUE THREAD

**Issue by flfsbr** [ctubio/Krypto-trading-bot#1026] opened 2020-05-02 02:23 UTC
I've been getting this error message for a few days:
05/02 02:17:53.290309 GW HITBTC Warrrrning: Error or ignored response: {"error":{"code":500,"description":"","message":"Internal Server Error"},"id":6499,"jsonrpc":"2.0"}.
Every time the bot buy or sell an error message like this immediately appears.
I opened a ticket in support and they answered that there was nothing wrong with the API or with my account.

Is anyone else constantly receiving this error message?
Is it a request that the bot is making incorrectly or is it a response that the bot is interpreting incorrectly?

**Comment by ctubio** [comment] 2020-05-02 04:16
i found little type mismatches on hitbtc while canceling orders (same value sometimes is a string and sometimes is a number), maybe we are talking about the same, lemme fix hitbtc type mismatches soOn''''

ty for the report''''

**Comment by ctubio** [comment] 2021-01-30 16:51
i cannot reproduce this,  hope is fixed by now; let me close this issue

**Closed by ctubio** 2021-01-30 16:51 UTC
Labels: :fire: fixme!
