### ISSUE TITLE
Bitmex: Missing Orders

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#989] opened 2019-08-22 21:10 UTC
There was another thread on this that talks about executed orders not showing up on K.
I think this is a real issue and not the accumulation problem because regardless of the trade long on the K web interface, the K console log should still properly show whenever any trade is executed and I have 12 trades worth of a position on actual Bitmex when the console log shows 9 trades after maybe 2 minutes of running.
This is a major problem and my assumption is that it has to do with lag and orders that the bot thought were cancelled not being cancelled, etc.

**Comment by ctubio** [comment] 2019-08-23 01:27
on XBTUSD? aaand can you let me know to what quantity of contracts are you setting your orders? so i can try with somewhat the same? cos for now i was not able to reproduce it i would say

thanks for the report'¡

**Comment by MiningInMySleep** [comment] 2019-08-23 01:41
I'm testing on minimum order so 26 contracts. Current settings are BBO, Mid mode, boomerang both sides, average ping fair. SOP off. BW off. Ping/Pong at .5 each.

**Comment by ctubio** [comment] 2019-08-23 01:53
yea im sorry for the mess of values, currently they are multiplied by price, will be fixed on next commit

and replaced prices too cos currently are not updated in the UI

**Closed** 2019-08-23 03:19 UTC
Labels: :fire: fixme!

**Comment by Corfucinas** [comment] 2019-08-23 03:21
@ctubio 

Thank you!

**Comment by ctubio** [comment] 2019-08-23 03:59
![922](https://user-images.githubusercontent.com/1634027/63565754-892ace80-c56a-11e9-9bb8-a5ca4ac331ae.gif)
