### ISSUE TITLE
libc 2.25 problem on Debian 9.5

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#819] opened 2018-09-30 11:29 UTC
Hi,
I can't use the latest K because it needs libc 2.25 and Debian (9.5) only has 2.24 on board.

"./K: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./K)"

Would it be possible to downgrade K so it will run again on Debian 9.5.

Thanks!

**Comment by ctubio** [comment] 2018-09-30 16:47
moriing'''
i can consider to downgrade sure but first i will like to try to keep the latest; it will take me a few days; meanwhile you can also consider https://linuxconfig.org/how-to-upgrade-debian-9-stretch-to-debian-10-buster in case you dont wanna wait for me

many thanks for the reprot'''

**Comment by Pat71** [comment] 2018-09-30 17:15
Hm, ok I like running "stable" OS and not "testing" ;-) 

(deb10 stable is planned for autumn 2019)

**Comment by flfsbr** [comment] 2018-09-30 21:02
Same error on ubuntu 16.04

**Comment by ctubio** [comment] 2018-10-01 01:35
ubuntu 18.04 should work fine and is already released

see https://packages.ubuntu.com/bionic/libc-bin and https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes and

**Comment by MiningInMySleep** [comment] 2018-10-01 11:53
Still getting the error after updating to the most recent release.

./app/server/K: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./app/server/K)
K crashed with exit code 1.. Respawning..

Debian 9.5

**Comment by ctubio** [comment] 2018-10-01 11:58
i really recommend you to upgrade your OS (https://linuxconfig.org/how-to-upgrade-debian-9-stretch-to-debian-10-buster)

im not friend of downgrades and im afraid it will take me many days to do if i ever do :S

**Comment by Pat71** [comment] 2018-10-01 12:05
that's sad :-(
Since I want my server to remain "stable", I will upgrade to deb10 next autumn (when it's stable)...so it means 1 year no K upgrade for me :-(

**Comment by ctubio** [comment] 2018-10-01 12:34
i understand your situation and i will try to provide a fix or a final statement asap, but i need to say meanwhile that debian is not ubuntu or macos or windows; debian testing is far more trusted than whatever ubuntu or macos or windows stable version out there, anyway, let me try some fix on next days :dancer: (i hope for a fix instead of downgrade yet, maybe ina week the plan changes to just downgrade if this error refuses to be fixed; but then i will be sad if c++11 is back xD)

**Comment by nonkreon** [comment] 2018-10-01 15:43
Hi Carles,
I'm against downgrades by philosophy as well, but my deal with Amazon prevents me from upgrading to GLIBC 2.25 for another 2 months or so 😢 how about we downgrade to the build where glibc 2.25 was not required (I believe it came when you upgraded to c++ 2017 right? solid upgrade in spirit btw) and stick there until we can upgrade glibc.
How do we install the last build that works with glibc-2.17?

**Comment by ctubio** [comment] 2018-10-01 16:41
well you know what? i really dont like to loose time; and fixing temporal errors is useless, lets downgrade and welcome c++17 next year :(

**Comment by ctubio** [comment] 2018-10-01 16:49
:koala: thanks for your patience and quick reports'' this way 0 commits were catched in between :D

**Comment by ctubio** [comment] 2018-10-06 18:57
im sorry after a 5 days i find myself not wanting to downgrade, also not wanting to fix it; i really suggest to launch a new machine with a newer OS (Debian 10 or latest ubuntu) or upgrate using standard upgrade distribution commands (https://linuxconfig.org/how-to-upgrade-debian-9-stretch-to-debian-10-buster), or if because reasons is not possible im really sorry but only solution is to follow the suggestion of @nonkreon and use v0.4.10.52, i will try to not remove it for some months

downgrade is not possible because for some reason now on c++11 `libquickfix` fails to initialize ssl connection using `llibopenssl`, i donno why, no error, no nothing, and im tired of it

fix it is not possible because still `getaddrinfo` and `gethostbyname_r` are used from libc; the alternative is to use `libcares` as a DNS resolver but is a pain to recode `libquickfix` and `libuWS`  to use it; by now only `libcurl ` uses it; so libc is still a dependency and build/runtime versions still must mach

**Comment by nonkreon** [comment] 2018-10-06 21:40
don't beat yourself up Carles, all you did was to advance your project to better, you shouldn't be sorry. We old timers know that the issue is on our side, what it is and will eventually catch up with you ☮️

**Comment by ctubio** [comment] 2019-01-05 01:02
:koala: lets close thiz now that github has released pinned issues

**Comment by ctubio** [comment] 2019-03-08 05:57
i think it will be fixed once https://github.com/ctubio/Krypto-trading-bot/pull/894 is merged; super @fuzzyTew fixed it

**Comment by Pat71** [comment] 2019-03-08 10:17
Yeah! :-)

**Closed** 2019-03-13 01:56 UTC
Labels: :heavy_check_mark: acknowledged, :skull: bug

**Comment by Pat71** [comment] 2019-03-13 19:36
Sadly, this still does not work on Debian 9.8:
"Makefile:91: *** K require g++ v7 or greater, but it was not found."
(Deb9 has g++v6)

**Comment by ctubio** [comment] 2019-03-13 20:12
:koala: that is another issue, you need to install g++7 or 8

Add to your ´/etc/apt/sources.list´ the debian experimental repo, see https://wiki.debian.org/DebianExperimental
then:
```
$ sudo apt-get update
$ sudo apt-get -t experimental install gcc-7
```

**Comment by Pat71** [comment] 2019-03-13 20:56
Thanks, but there's only gcc-9 in experimental: https://packages.debian.org/experimental/devel/

I'll keep looking for gcc-7...

**Comment by ctubio** [comment] 2019-03-13 21:11
with gcc 9 should work too, just need to update the Makefile to allow v9 as well as 8 and 7

**Comment by ctubio** [comment] 2019-03-15 00:25
after 829a0c448e5d1f711a4ad98963483a5df8f5cd2a i believe you will not be asked to recompile anymore (but you can do if you wish)
