### ISSUE TITLE
Bug: Width is not respected if there is a "TBP Held"

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#329] opened 2017-10-25 08:19 UTC
When TBP Held is activated, the width of the side trading is not respected. (at least in %).

In any case, Bid price should be equal = FV - Width /2
and Ask price = FV + width /2

Can you please have a look at that?

Best :)

**Comment by Camille92** [comment] 2017-10-25 08:23
Mode used : Top

**Comment by b-seite** [comment] 2017-10-25 19:17
Hmm...
I am not sure but i think its because the quoting engine sets the price&size of a side with a trading ban to 0. 
But real values are needed during calculation for the other sides quotes. 
The solution could be to check if qeBidState is not live immediately before send the quote and get rid of the awQuote.ask.price = 0 etc.
But its jus a guess

**Comment by Camille92** [comment] 2017-10-26 09:25
why not!

Or why not simply defining a quote from FV (that is always here) rather than the other side?
So whatever happens a quote can still be defined!

**Comment by b-seite** [comment] 2017-11-01 09:27
Hey Camille,

crawled trough the code but i did not find any issues that could lead us to a solution for your problem.
But i find this #353 (on ask side with is not respected correctly)
Maybe that helps you. Can you check, if its your solution?

**Comment by b-seite** [comment] 2017-11-17 15:34
I think, we can close this one. 
Problem seems to be fixed or did anybody still see is?

**Comment by ctubio** [comment] 2017-11-26 03:48
to me nextQuote looks nice :S cannot imagine how width may be not respected no matter what is the current status :S

**Comment by ctubio** [comment] 2017-11-26 18:44
i really cannot reproduce this, i see width always respected, aslo with TBPHelp enabled i can play with width values and are always respected for next quotes

**Closed by ctubio** 2017-11-26 18:44 UTC
Labels: bug, non reproducible bug
