### ISSUE TITLE
Filled orders not registering in UI

### ISSUE THREAD

**Issue by halessi** [ctubio/Krypto-trading-bot#946] opened 2019-06-05 16:08 UTC
Hello,

Using Coinbase and while trading LTC/BTC, filled orders are not registering in the UI. I've been  using the Coinbase Pro website to confirm this -- the fills register there but never appear in the history of trades.

I'm using Top/AK47. Thanks for your help.

**Comment by ctubio** [comment] 2019-06-05 16:55
morniing''
i can't believe this is happening but will triple check before close the issue (cos since a week ago we have new websocketz)

let me come back againz soOn''

**Comment by halessi** [comment] 2019-06-05 16:57
yeahh i'll toy w some different settings to make sure i'm not just being an idiot

**Comment by ctubio** [comment] 2019-06-05 17:00
just saying, i think any settings should not matter, cos without conditions every new filled order must print a log message in the CLI and also update the UI tables

if you are missing some CLI log messages, we have a issue here
if you see CLI log messages but you are missing updated in the UI tables, we may have a missunderstanding somewhere (not a issue)

hope ^thiz helps you meanwhile i investigate toO''

thanks for your time'''

**Comment by halessi** [comment] 2019-06-05 18:49
closing this as CLI log appears w/ boomerang and top so not sure what was happening but assuming i messed up somehow

**Comment by ctubio** [comment] 2019-06-05 21:14
maybeee, the confusion was because 2 (or more) trades with the same price got accumulated in the history of trades?

note that the table of history of trades in the UI tries to be as small as possible while accumulating quantities of trades of the same price and same side

**Comment by halessi** [comment] 2019-06-05 22:27
i'm pretty certain somethings happening -- it might be intended/not an error, but i still need help understanding. 

<img width="1351" alt="Screen Shot 2019-06-05 at 6 23 42 PM" src="https://user-images.githubusercontent.com/34874946/58994755-9d5afd00-87bf-11e9-9352-e6d014c37888.png">

as can be seen in this screenshot, the most recent buy order does not appear in the history of trades. the one buy order that is shown corresponds with the 2nd most recent buy in the history. if you could help explain this it would be much appreciated. thank you.

**Comment by ctubio** [comment] 2019-06-06 11:55
i was not testing with ak47, let me try with it thiz afternoOn; thanks'¡

**Comment by ctubio** [comment] 2019-06-06 17:18
can you please confirm that your cpu is not very high? (with for example `htop` command?)

if your cpu usage is very high, means the bot is delayed in time a few seconds/minutes and another kind of solution is required

**Comment by ctubio** [comment] 2019-06-07 14:41
im sorry i carefuly tested it but im not able to reproduce it; i can see all orders fine in the UI; i think the problem is because ak47 is too much aggressive and may hit api limits :S so maybe a `--lifetime` argument helps to reduce the api calls and still keep 10 bullets on each side?

**Closed by ctubio** 2019-06-07 14:41 UTC
Labels: :fire: fixme!
