### ISSUE TITLE
Different Completed Trade Quantity

### ISSUE THREAD

**Issue by MiningInMySleep** [ctubio/Krypto-trading-bot#823] opened 2018-10-06 10:46 UTC
There seems to be an issue where quantity traded is recorded incorrectly in the online interface.

https://i.imgur.com/vu6IQ97.png
https://i.imgur.com/l8mtegm.png

The 109 value is the correct one as confirmed with the exchange. It wasn't a partial order.

**Comment by serzhiio** [comment] 2018-10-06 10:49
Support this ticket. I have same problem on BFX.

**Comment by MiningInMySleep** [comment] 2018-10-07 01:10
Could this be happening because the bot combines new trades that have not been filled with old trades for the same price that haven't been filled?

**Comment by ctubio** [comment] 2018-10-08 17:19
yea trades are accumulated on K UI if have same price; then timestamps are overwrited, price remains, and quantities are accumulated

let me discard is not a real bug before close the issue

**Comment by ctubio** [comment] 2018-10-08 17:52
yea this is intended behavior

:bulb: on `PingPong`mode quantities are not accumulated

let me close the issue :dancer:

**Closed by ctubio** 2018-10-08 17:52 UTC
Labels: fixme!
