### ISSUE TITLE
Hitbtc Order book stays empty

### ISSUE THREAD

**Issue by Pat71** [ctubio/Krypto-trading-bot#597] opened 2018-01-24 08:30 UTC
since yesterday, there is a 50/50 chance that the orderbook keeps empty. I tried make reinstall, restart and even deleting the database. I'm using the full version.
 
Exchange: HITBTC, effect occurs on every coin.

Console log seems ok:
08:26:25.747768 GW HITBTC WS Streaming book levels and orders.

**Comment by serzhiio** [comment] 2018-01-24 08:35
I believe its not a bug of K but of HitBTC ws API. Im expiriencing the same since morning of 23 jan. 
Anyway Carles please check it up.

**Comment by Pat71** [comment] 2018-01-24 08:47
Update: since today's reinstall, the order book never comes up :-( (eos/usd trx/usd)

**Comment by keeroo1337** [comment] 2018-01-24 10:33
While Using the unlocked bot on HitBtc, I have also experienced this since yesterday afternoon (Jan. 23rd). The console output of K writing the current TBP and pDiv seems also to be less frequent than before. 

From my point of view, it is either potentially related to the latest commits about asynchronous functionality or it is caused by the HitBTC API itself. 

However, this is just speculation from my side. I just wanted to confirm that I have also this issue.

**Comment by grhangelone** [comment] 2018-01-24 12:48
ok, i tested a little bit

free version without money and stopped - orderbook updates work
regged version without money and stopped - orderbook updates work
free version without money and started - orderbook updates work
regged version without money and started - orderbook updates work

free version started with money:
stopped updating orderbook and trades after 10min:
without any errormessage

[...]
11:42:25.289763 QE Warrrrning: Unable to calculate quote, missing market data.
11:42:25.318381 UI 1 currently connected, last connection was from 192.168.2.96.
11:42:25.438461 GW HITBTC Quoting state changed to CONNECTED.
11:42:25.438954 GW HITBTC WS Streaming book levels and orders.
^C
11:54:22.704603 Excellent decision! Chuck Norris went out of an infinite loop.
11:54:22.705074 GW HITBTC Quoting state changed to DISCONNECTED.
11:54:22.705397 GW HITBTC Attempting to cancel all open orders, please wait..
11:54:22.909265 GW HITBTC cancell all open orders OK.
11:54:22.910630 UI 0 currently connected, last connection was from 192.168.2.96.
11:54:22.911057 K exit code 0.

![free-version-9min no update](https://user-images.githubusercontent.com/35765416/35332799-9792285c-010c-11e8-89f4-de46416546b7.jpg)




the regged version worked for some time and then just freezed
without any errormessage
angelone@server2:~/ramdisk/K$ ./angelone.sh --currency eth/usd --autobot
K build x86_64-linux-gnu 2018-01-22 20:17:23.
K version unknown (zip install).
11:54:35.339342 DB data/angelone.db loaded OK.
11:54:35.340165 UI ready over HTTPS on external port 3000.
11:54:35.341007 DB loaded Quoting Parameters OK.
11:54:35.341335 DB loaded 0 historical Trades.
11:54:35.341667 DB loaded 0 STDEV Periods.
11:54:35.341942 DB loaded 978.897388 EWMA VeryLong.
11:54:35.342108 DB loaded 1004.389329 EWMA Long.
11:54:35.342253 DB loaded 1005.073814 EWMA Medium.
11:54:35.342396 DB loaded 1005.127676 EWMA Short.
11:54:35.343133 DB loaded 96 historical FairValues.
11:54:35.343407 DB loaded 2 historical Profits.
11:54:35.343711 DB loaded TBP = 0.00363224 ETH.
11:54:35.743071 GW HITBTC allows client IP.
11:54:35.743467 GW HITBTC:
- autoBot: yes
- symbols: ETHUSD
- minTick: 0.01000000
- minSize: 0.00100000
- makeFee: 0.00000000
- takeFee: 0.00000000.
11:54:36.398321 QE Warrrrning: Unable to calculate quote, missing market data.
11:54:36.587504 GW HITBTC Quoting state changed to CONNECTED.
11:54:36.588037 GW HITBTC WS Streaming book levels and orders.
11:54:40.069798 UI 1 currently connected, last connection was from 192.168.2.96.
11:55:18.596365 GW HITBTC TRADE BUY  0.003 ETH at price 1004.16 USD (value 3.01248 USD).
11:56:33.581810 GW HITBTC TRADE BUY  0.003 ETH at price 1004.05 USD (value 3.01215 USD).
12:01:40.190815 GW HITBTC TRADE SELL 0.003 ETH at price 1014.46 USD (value 3.04338 USD).
12:02:30.114659 GW HITBTC TRADE BUY  0.003 ETH at price 1012.96 USD (value 3.03888 USD).
12:04:26.259524 GW HITBTC TRADE SELL 0.003 ETH at price 1012.16 USD (value 3.03648 USD).
12:04:30.187619 GW HITBTC TRADE BUY  0.003 ETH at price 1009.61 USD (value 3.02883 USD).
12:04:31.474243 GW HITBTC TRADE SELL 0.003 ETH at price 1011.66 USD (value 3.03498 USD).
12:05:18.359045 GW HITBTC TRADE BUY  0.003 ETH at price 1008.09 USD (value 3.02427 USD).
12:05:38.555296 GW HITBTC TRADE SELL 0.003 ETH at price 1008.49 USD (value 3.02547 USD).
12:08:08.463859 GW HITBTC TRADE BUY  0.003 ETH at price 1008.29 USD (value 3.02487 USD).
12:14:59.606097 GW HITBTC TRADE SELL 0.003 ETH at price 1012.14 USD (value 3.03642 USD).
12:14:59.743303 GW HITBTC TRADE SELL 0.003 ETH at price 1011.86 USD (value 3.03558 USD).
12:19:04.027208 GW HITBTC TRADE BUY  0.003 ETH at price 1012.22 USD (value 3.03666 USD).
12:21:36.750094 GW HITBTC TRADE BUY  0.003 ETH at price 1013.93 USD (value 3.04179 USD).
12:22:44.624001 GW HITBTC TRADE SELL 0.003 ETH at price 1018.92 USD (value 3.05676 USD).
12:25:49.110195 GW HITBTC TRADE BUY  0.003 ETH at price 1023.71 USD (value 3.07113 USD).
^C
12:30:08.864292 Excellent decision! Don't worry about tests, Chuck Norris's test cases cover your code too.
12:30:08.864790 GW HITBTC Quoting state changed to DISCONNECTED.
12:30:08.865181 GW HITBTC Attempting to cancel all open orders, please wait..
12:30:09.073754 GW HITBTC cancell all open orders OK.
12:30:09.074643 UI 0 currently connected, last connection was from 192.168.2.96.
12:30:09.075138 K exit code 0.

![regged-version stopped updating after some trades](https://user-images.githubusercontent.com/35765416/35332800-97b59968-010c-11e8-84e5-f788be903ace.jpg)



the "without error message" part is new to me.
yesterday i usually got the message

10:21:34.631450 GW HITBTC WS Disconnected, reconnecting in 10s..

this results in two effects:
1) sometimes the gui flickers to red and then back to green and i have zombie orders but other than that it works as expected
2) the orderbook disappears completely, i get trades with fantasy-values 10% below the current fair value (which sadly sometimes get filled in)
and the trades on the right don't update
(sorry, no screens)

the second effect is a total showstopper.
luckily i just had a small amount of ETH on the account
but the fair value was at around 1k usd for eth
the bot traded merrily for an hour or so.
then the gui flickered, the orderbook disappeared and the fair value switched to 850usd
the bot then made a sell order @ 851 which was immediately filled in
the following buy order at 850 was never filled, which stopped further loss

**Comment by zmbbmz** [comment] 2018-01-24 13:20
yepp, same problem here.

it takes 5-6 restarts now, to get the order book working on the unlocked bot (hitbtc).
this strange behavior started a few days ago with EBTCNEW coin.

**Comment by Pat71** [comment] 2018-01-24 18:07
Seems like a HITBTC problem: https://github.com/hitbtc-com/hitbtc-api/issues/113

**Comment by ctubio** [comment] 2018-01-24 18:17
the problem is that hitbtc api only send orderbook snapshots, and is not sending orderbook updates.

K after connecting gets a snapshot, and thats why X amount of market levels are noted in the footer, but then Hitbtc do not send market updates, and since the UI only shows content after a market update, the UI looks like no market data at all.

ima not modify nothing in K and wait for hitbtc news

**Comment by ctubio** [comment] 2018-01-29 18:01
lets close this as seems there is nothing to do here :dancer;

**Closed by ctubio** 2018-01-29 18:01 UTC
Labels: acknowledged
