### ISSUE TITLE
Coinbase Fees not calculating properly

### ISSUE THREAD

**Issue by OverlordQ** [ctubio/Krypto-trading-bot#926] opened 2019-04-09 18:07 UTC
```
04/09 18:04:09.538726 GW COINBASE cached handshake:
- gateway: https://api.pro.coinbase.com
- gateway: wss://ws-feed.pro.coinbase.com
- gateway: fix.pro.coinbase.com:4198
- autoBot: yes
- symbols: BCH/USD
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00%
- takeFee: 0.00%.
```

Fees can be found here: https://support.pro.coinbase.com/customer/en/portal/articles/2945310-fees

You can get your [current trading volume](https://docs.pro.coinbase.com/#trailing-volume) with `GET /users/self/trailing-volume`

**Comment by ctubio** [comment] 2019-04-10 11:59
:koala: you are right; let me finnish the current commits and the issues of fees will be fixed next (hopefully soOn)

many thanks for the report'''

**Comment by ctubio** [comment] 2019-04-15 01:36
well, lets first merge https://github.com/ctubio/Krypto-trading-bot/pull/921

**Comment by ctubio** [comment] 2019-04-15 22:12
well after mergin  #921 i dont think it helps :D but we are closer

:koala: lets see what is this coinbase api you suggest; many thanks'¡

**Comment by ctubio** [comment] 2019-04-20 13:23
ok after mergin https://github.com/ctubio/Krypto-trading-bot/pull/922 makes sense to add coinbase fees cos then fees will be really in use :D

**Comment by ctubio** [comment] 2019-05-20 00:34
i think is a bit messy to read automatically the fees from coinbase cos the endpoint of returns something like:
```
[{"exchange_volume":"67085.66416230","product_id":"BTC-EUR","recorded_at":"2019-05-20T00:05:00.003178Z","volume":"1.10258208"}]
```

the problem is that coinbase fees are in dollars (the minimum fee level is < $100K)

so we need to translate 1.10258208 BTC to USD, and currently that bot was only about BTC-EUR, so have no idea about USD (and the same happens with other currencies, all volumes of all currencies needs to be translated to USD to know the fee limitz see "How are taker fees calculated?" section at https://support.pro.coinbase.com/customer/en/portal/articles/2945310-fees)

meanwhile they not provide an easy 1 call api, i think is more efficient to manually introduce this values :S (also fees by coinbase are translated to USD at the time of filling the orders, not at the time of reading volumes, so is double useless to try to calculate coinbase fees if you ask me :S)

hope yoU agree if we close thiz issue'¡ (otherwise feel free to do like me and send a support ticket to coinbase asking for an endpoint to get user's fees [or even better, to make fees equal for everybody like in a fair world])

thanks for your patience on this (manually solved) issue'¡

**Closed by ctubio** 2019-05-20 00:34 UTC
Labels: :gift_heart: improvement, :heavy_check_mark: acknowledged
