### ISSUE TITLE
Bot keeps sending orders even if no funds available [BITMEX]

### ISSUE THREAD

**Issue by nonkreon** [ctubio/Krypto-trading-bot#1027] opened 2020-05-04 17:59 UTC
I haven't noticed it happening anywhere, on Coinbase it says 'depleted funds', but it keeps submitting new orders on Bitmex.
![image](https://user-images.githubusercontent.com/3709448/80997511-6e09a180-8e0f-11ea-9234-a9e6a650c874.png)
For non-USD pair example, EOSM20:
![image](https://user-images.githubusercontent.com/3709448/81014977-da929980-8e2b-11ea-97bf-2a36727bc627.png)

**Comment by ctubio** [comment] 2021-01-29 01:30
i was able to reproduce it; let fix this next'¡

:koala: many thanks for the report and sorry for taking so long

**Comment by ctubio** [comment] 2021-01-30 01:36
:koala: the issue is that we are working with `order values` instead of `order costs`; and costs is what is deduced from the available balance while palcing orders

lemme paste here the formula:
```
Order Value = 1/Price * Contract Quantity
Order Cost = (1/Leverage) * Order Value + (2 * (Taker Fee * Order Value))
```

**Comment by ctubio** [comment] 2021-01-30 05:43
sooo.. after next commit, the bot will not try to open orders bigger than what is possible

but it was done finally without using the order cost formula; just making sure sell orders are not bigger than buy orders; this way also the contract ina open position match the contracts ina closing position

makes sense to me if you ask me; but let me know if you disagree
thank you'¡

**Closed** 2021-01-30 05:53 UTC
Labels: :fire: fixme!, :heavy_check_mark: acknowledged
