### ISSUE TITLE
 Signal 6 Aborted(Three-Headed Monkey found)

### ISSUE THREAD

**Issue by tkupka** [ctubio/Krypto-trading-bot#685] opened 2018-03-18 18:45 UTC
Application dies after few minutes on KRAKEN exchange

- upstream: KRAKEN
- currency: ETH/EUR
- roll-out: 1521398456201
- lastbeat: 1521398598240
- os-uname: Linux 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64
- tracelog:
./app/server/K(_ZN1K2EV3wtfEi+0x8eb) [0x7f716e30166b]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7f716d495cb0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7f716d495c37]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f716d499028]
./app/server/K(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d) [0x7f716e6ce90d]
./app/server/K(_ZN10__cxxabiv111__terminateEPFvvE+0x6) [0x7f716e645ce6]
./app/server/K(+0x4c6d31) [0x7f716e645d31]
./app/server/K(+0x4c702a) [0x7f716e64602a]

**Comment by ctubio** [comment] 2018-03-23 18:14
im sorry im not able to reproduce this (and this tracelog is not usefull :(); can you paste the output of the app running with valgrind? (by uncommenting valgrind in the bottom of the config file?)

thanks''

**Comment by ctubio** [comment] 2018-03-27 17:23
closing cos im not able to reproduce it; please consider to paste the output of valgrind if you still are facing this issue and wanna get it fixed; thanks'''

**Closed by ctubio** 2018-03-27 17:23 UTC
Labels: fixme!
